"""empty message

Revision ID: 8c0679649449
Revises: 
Create Date: 2020-04-06 14:28:54.211563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0679649449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('emailAddress', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emailAddress'),
    sa.UniqueConstraint('username')
    )
    op.create_table('postinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('cp', sa.String(length=255), nullable=True),
    sa.Column('trestbps', sa.String(length=255), nullable=True),
    sa.Column('chol', sa.String(length=255), nullable=True),
    sa.Column('fbs', sa.String(length=255), nullable=True),
    sa.Column('restecg', sa.String(length=255), nullable=True),
    sa.Column('thalach', sa.String(length=255), nullable=True),
    sa.Column('exang', sa.String(length=255), nullable=True),
    sa.Column('oldpeak', sa.String(length=255), nullable=True),
    sa.Column('slop', sa.String(length=255), nullable=True),
    sa.Column('ca', sa.String(length=255), nullable=True),
    sa.Column('num', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['postinfo.id'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('postinfo')
    op.drop_table('user')
    # ### end Alembic commands ###
