"""empty message

Revision ID: e428fd1ba4e2
Revises: f74338b76ecd
Create Date: 2020-04-08 16:57:11.597210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e428fd1ba4e2'
down_revision = 'f74338b76ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'postinfo', 'user', ['userid'], ['id'])
    op.create_foreign_key(None, 'result', 'postinfo', ['postid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_constraint(None, 'postinfo', type_='foreignkey')
    # ### end Alembic commands ###
