"""empty message

Revision ID: f74338b76ecd
Revises: 8c0679649449
Create Date: 2020-04-08 16:54:31.731794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f74338b76ecd'
down_revision = '8c0679649449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'postinfo', 'user', ['userid'], ['id'])
    op.add_column('result', sa.Column('result_m', sa.String(length=255), nullable=True))
    op.add_column('result', sa.Column('result_s', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'result', 'postinfo', ['postid'], ['id'])
    op.drop_column('result', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('result', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'result_s')
    op.drop_column('result', 'result_m')
    op.drop_constraint(None, 'postinfo', type_='foreignkey')
    # ### end Alembic commands ###
